### PR TITLE
Create an ids_reader for indirect containers

### PR DESCRIPTION
**Pull request by jcoyne**
This will enable us to resolve a performance concern.
see https://github.com/projecthydra-labs/hydra-pcdm/issues/193

### CODE REVIEW

**Comment by jcoyne** [comment]
Please don't merge this yet. I have a few concerns.

**Comment by jcoyne** [comment]
Okay, concerns addressed. Ready for review.

**Comment by tpendragon** [comment]
I'm going to have to pull this locally and check. Have some concerns about what happens when there's persisted items, it's reloaded, and then you concat in memory items

**Comment by mjgiarlo** [comment]
Waiting on @tpendragon's assessment.

**Comment by tpendragon** [comment]
Ah, that's actually what the second test does, wasn't reading it right because of the reloaded let.

**Pull request merged**
