### PR TITLE
Can assign single ActiveTriples::Resource to single-valued attribute (fi...

### PR DESCRIPTION
**Pull request by dchandekstark**
...xes #653)

Bumped version to 8.0.0.rc3

### CODE REVIEW

**Comment by dchandekstark** [comment]
If this passes Travis and gets :+1: 'd I'd propose making this 8.0.0 final.

**Comment by dchandekstark** [comment]
Ping @jcoyne @terrellt @mjgiarlo

**Comment by terrellt** [comment]
@dchandekstark :+1: I assume this works like AT, in that if I set a property to an AT::Resource it sets it to a URI which spins up a resource on access.

**Comment by dchandekstark** [comment]
@terrellt No change in how the property setting works per se, this just fixes #653 which would not permit setting a single-valued AF model attribute to an AT Resource b/c an AT::Resource is an RDF::Graph, which is an enumerable.

**Comment by mjgiarlo** [comment]
:ok_hand: by me.

**Comment by terrellt** [comment]
Are there tests already ensuring that you can set a property to an AT::Resource and get it back out?

**Comment by dchandekstark** [comment]
@terrellt Dunno, but that would be a separate issue, right?

**Comment by terrellt** [comment]
> @terrellt Dunno, but that would be a separate issue, right?

Maybe? This PR specifically allows something that could be broken. If that's okay with the community, then I yield to that judgement. @mjgiarlo @jcoyne ?

**Comment by dchandekstark** [comment]
@terrellt Not exactly.  What's being allowed here was allowed in version 7 (with a deprecation warning).  In Version 8 it breaks because you can't set the value of single-valued attribute to something that responds to :each (prior to this PR).  That condition was written with Array in mind -- it wasn't intended to apply to an AT::Resource.  If there's a deeper issue here, I need more context.  It's possible that something *is* broken, although I don't see this PR as doing the breaking.

**Comment by jcoyne** [comment]
:+1:

**Pull request merged**
