### PR TITLE
Version 8.1.0

### PR DESCRIPTION
**Pull request by dchandekstark**
Patches casting behavior (#777).

### CODE REVIEW

**Comment by dchandekstark** [comment]
Proposing a new minor version due to this change.

**Comment by mjgiarlo** [comment]
:+1: :ok:

**Comment by jcoyne** [comment]
Can you update the changelog as well?

**Comment by mjgiarlo** [comment]
FWIW, @dchandekstark, I don't think you need the PR process for this (though you're of course welcome to use it for more feedback).  You can follow the steps here for pushing out a release:

https://github.com/projecthydra/active_fedora/wiki/Release-management-process#activefedora-release-management-step-by-step

(Includes the step @jcoyne just asked you to take.)

**Comment by dchandekstark** [comment]
@jcoyne @mjgiarlo Got it, thanks.

**Comment by dchandekstark** [comment]
@mjgiarlo I think @jcoyne means History.txt, which is not in the doc.

**Comment by mjgiarlo** [comment]
@jcoyne made that change, wherein he suggests using GitHub release notes instead of History.txt:

https://github.com/projecthydra/active_fedora/wiki/Release-management-process/_compare/ac1ebe250383a4018398f64c9c36e07325027132...c6d1bc90f92bf2184b7c81a814faae08ab96efbd

@jcoyne So should we stick with History.txt or GitHub release notes or both?

**Comment by dchandekstark** [comment]
@mjgiarlo @jcoyne If you use the release notes, I think the process would be slightly different b/c you would release first, and then edit the release for the tag created.  Right?

**Comment by dchandekstark** [comment]
@jcoyne @mjgiarlo Are we ready to roll?

**Comment by mjgiarlo** [comment]
I was kinda waiting on @jcoyne to clarify the release note process so we have clarity in the future as to whether we update History.txt, GitHub release notes, or both.

**Comment by jcoyne** [comment]
Hold off on releasing 8.1.0. I'm working on a serious bug.

@mjgiarlo I dunno.

**Comment by jcoyne** [comment]
@dchandekstark please add this to your branch before releasing: https://github.com/projecthydra/active_fedora/pull/783/files

**Comment by dchandekstark** [comment]
@jcoyne Will do.

**Comment by dchandekstark** [comment]
@jcoyne Your PR is on master. You want me to backport this to 8.x-stable?

**Comment by dchandekstark** [comment]
@jcoyne I'm not sure this patch can be applied as is. Can you work up a backport?

**Comment by dchandekstark** [comment]
@jcoyne ping

**Comment by jcoyne** [comment]
@dchandekstark sorry, I don't have time to do that. I'm not running AF 8 anywhere either, so I don't have much interest in pursuing that.

**Comment by dchandekstark** [comment]
@jcoyne OK, then can we go ahead and push out 8.1.0 as is? @mjgiarlo

**Comment by mjgiarlo** [comment]
Go for it, @dchandekstark.  Sorry this got held up!

**Pull request merged**
