### PR TITLE
Support basic authorization to Fedora

### PR DESCRIPTION
**Pull request by awead**
Addresses #716 and provides support for making connections to Fedora using basic authorization.

### CODE REVIEW

**Comment by awead** [comment]
@jcoyne for your consideration. We should probably cut a new LDP release instead of pinning to @cbeer  master branch.

**Comment by jcoyne** [comment]
@awead bug @cbeer about getting adding yourself to his repo. Otherwise ask if we can move ldp to projecthydra.

**Comment by cbeer** [comment]
I'm :+1: to moving it, if someone else does the paperwork.

**Comment by awead** [comment]
@cbeer all it would need is an Apache2 license to go into projecthydra-labs, which would be enough for now. However, @lasse-aagren doesn't seem to have a iCLA on file. Would that prevent it from going into any Hydra organization? @jcoyne ?

**Comment by mjgiarlo** [comment]
AFAIK, it would prevent inclusion under either Hydra org, @awead.

**Comment by awead** [comment]
@mjgiarlo yeah, that's what I was afraid of. Although Lasse is working for DTU, I believe. Do they not have a CLA with Hydra?

**Comment by lasse-aagren** [comment]
I'm a bit confused :) what do I need to do (or don't do)? :)

**Comment by lasse-aagren** [comment]
And yes, I work for DTU

**Comment by awead** [comment]
@lasse-aagren sorry, didn't mean to rope you into this. The issue is moving the ldp repo into a Hydra-based organization where it can have broader ownership and support. In order for this to happen, all committers have to have Committers License Agreements on file with us. I'm suspecting you don't, unless DTU has one with us. If you'd like to give us one, that would be great, and it would also allow you to directly contribute to all our other Hydra gems.

**Comment by cbeer** [comment]
@awead feel free to send a PR to update the license.

**Comment by awead** [comment]
@cbeer on the way

**Comment by lasse-aagren** [comment]
@awead I don't think we have one at DTU - but you certainly can have one from me for now. How do I do it?

**Comment by awead** [comment]
@lasse-aagren Great! Just send an email to `legal@projecthydra.org` saying you need to file an "Individual committers license agreement" with us. They should send you a form to sign. It's the standard Apache 2.0 license.

**Comment by lasse-aagren** [comment]
Great - will do, and let you know here, when it is order.

**Comment by awead** [comment]
@lasse-aagren Awesome, thank you! :clap:

**Comment by lasse-aagren** [comment]
it's in progress - just need my manager to nod that I have DTUs approval to contribute (that's just a formality)

**Comment by lasse-aagren** [comment]
signed iCLA sent to legal@...

**Comment by mjgiarlo** [comment]
@lasse-aagren Great!  We should be able to merge this as soon as Steering processes the paperwork.  Shouldn't be long now.  Thanks for your patience.

**Pull request merged**
