### PR TITLE
SolrHit#instantiate_with_json should create persisted objects

### LINKED ISSUE #1054: model returned by ActiveFedora::SolrHit. instantiate_with_json is persisted? -> false
active-fedora (9.10.4)
ldp (0.5.0)
rails (4.2.5.1)

this breaks polymorphic path builders, which will not create a show path for an unpersisted model.

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #1054

### CODE REVIEW

**Comment by cbeer** [comment]
@barmintor

**Comment by jcoyne** [comment]
What? That was the bug?  :+1:

**Comment by cbeer** [comment]
Not sure. It was one thing I tripped across trying to recreate the bug in the first place, and I'm hoping it's related.

**Comment by barmintor** [comment]
I am chasing down various dependency conflicts preventing me from testing this in my sufia7 app, the latest is that hydra-access-controls has not been released and is not a github repo, so it's released pin of AF ~> 9.10.x is in effect, barring AF master.

**Pull request merged**
