### PR TITLE
Support both Fedora and Premis predicates, supports Fedora 4.4

### PR DESCRIPTION
**Pull request by awead**
The fixity predicates have changed. We'll need to release a new version of AF once this is merged, but it requires an update to hydra-jetty.

### CODE REVIEW

**Comment by awead** [comment]
See projecthydra/hydra-jetty#39

**Comment by awead** [comment]
Is it worth modifying FixityService to support checks made to all versions of Fedora 4? This would mean querying for three difference predicates:

* ::RDF::Vocab::Fcrepo4.status
* ::RDF::URI("http://fedora.info/definitions/v4/repository#status")
* and the current Premis one

thoughts? @jcoyne @terrellt @mjgiarlo

**Comment by jcoyne** [comment]
I think we should probably attempt to support at least 4.4.0 and 4.3.0, so we should probably query for both URIs.  I think there are only 2 though. Aren't the first two bullet points the same predicate? It's just that it's no longer in the most recent version of rdf-vocab, which is why we moved it to a hard coded uri.

**Comment by awead** [comment]
@jcoyne yeah, that looks right. I'll update the PR.

**Comment by awead** [comment]
@jcoyne I tested it locally under Fedora 4.3 and 4.4, and all is well. Travis should be testing it using 4.4, now that hydra-jetty is updated.

**Pull request merged**
