### PR TITLE
Caching

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by terrellt** [comment]
Can we get a description about the use case and motivation of this feature? I know this kind of thing just happens in AR, right?

**Comment by jcoyne** [comment]
@terrellt if you run this in Rails, it injects a middleware that enables the cache at the beginning of the request.  Then if you ever ask for an object from LDP, it caches the response and returns the cached result.  At the end of the request the cache is cleared. If you have a list of N objects and you iterate over each to get an associated object (e.g. collection), you'd have N loads. This prevents extra loads if the associated object has already been loaded.

**Comment by jcoyne** [comment]
Here's an example of a log file on a page that has 3 GenericObjects all with the same Batch:
```
  Load GenericFile (0.1ms) 7eec95eb-b947-452f-96ce-f2134ca01807 Service: 70307049620960
  Load Batch (0.1ms) cd12db7f-dc18-4250-aa96-a51e3051770c Service: 70307049620960
  Rendered /Users/justin/workspace/sufia/app/views/my/_index_partials/_list_files.html.erb (186.4ms)
  Load GenericFile (0.1ms) d229dea8-a20c-46bd-8407-ec5f2f939f8c Service: 70307049620960
  CACHE (0.0ms) cd12db7f-dc18-4250-aa96-a51e3051770c Service: 70307049620960
  Rendered /Users/justin/workspace/sufia/app/views/my/_index_partials/_list_files.html.erb (191.7ms)
  Load GenericFile (0.1ms) bcda063e-e512-43b0-8ce8-46f4df0171f8 Service: 70307049620960
  CACHE (0.0ms) cd12db7f-dc18-4250-aa96-a51e3051770c Service: 70307049620960
```

**Comment by jcoyne** [comment]
Hmm, as the LDP request (to the server) is not done when the LdpObject is initialized, I'm afraid this doesn't have the benefits I was hoping for.

**Comment by jcoyne** [comment]
Okay, I've moved the caching to a lower level, caching the HTTP responses.  This means the cache is actually effective. :wink:  Please review for merge.

**Pull request merged**
